const state = { info: null, devices: [], activeDevice: null, peer: null, stream: null, captureProfile: localStorage.getItem('halo.captureProfile') || 'screen' };
const $ = (selector) => document.querySelector(selector);

const captureProfiles = {
  screen: { label: 'seluruh layar', surface: 'monitor', contentHint: 'detail', note: 'Profil aktif: seluruh layar · kualitas seimbang' },
  window: { label: 'jendela aplikasi', surface: 'window', contentHint: 'detail', note: 'Profil aktif: jendela aplikasi · pilih Spotify, browser, atau aplikasi lain pada dialog Windows' },
  lyrics: { label: 'preview lirik', surface: 'browser', contentHint: 'detail', note: 'Profil aktif: preview lirik · pilih tab atau jendela browser pada dialog Windows' },
  media: { label: 'Spotify / media', surface: 'window', contentHint: 'motion', note: 'Profil aktif: Spotify / media · pilih jendela aplikasi pada dialog Windows' },
};

function render(info) { if (!info) return; state.info = info; state.devices = info.devices ?? []; $('#top-address').textContent = info.address.replace('ws://', ''); $('#stat-ip').textContent = info.address.replace('ws://', '').split(':')[0]; $('#full-address').textContent = info.address; $('#activity-address').textContent = `${info.address} · WebSocket aktif`; $('#pin').textContent = info.pin; $('#qr').src = info.qrDataUrl; renderDevices(); renderCaptureProfile(); }
function renderDevices() { const devices = state.devices; $('#stat-devices').textContent = String(devices.length); $('#nav-device-count').textContent = String(devices.length).padStart(2, '0'); if (!devices.length) { $('#devices-list').innerHTML = '<div class="empty-device"><div class="empty-orbit"><span>⌁</span></div><div><strong>Menunggu Pocket Hub</strong><p>Scan QR di atas untuk menambahkan HP pertama Anda ke jaringan lokal.</p></div><span class="empty-code">READY / 0 DEVICES</span></div>'; return; } $('#devices-list').innerHTML = devices.map((device) => `<div class="device-card"><div class="device-avatar">${device.platform.toLowerCase().includes('android') ? '▣' : '⌁'}</div><div class="device-main"><strong>${escapeHtml(device.name)}</strong><small>${escapeHtml(device.platform)} · Terhubung ${formatSince(device.connectedAt)}</small></div><div class="device-status"><i></i> TERHUBUNG</div><button class="device-action primary" data-screen="${escapeHtml(device.id)}">Kirim layar</button><button class="device-action" data-disconnect="${escapeHtml(device.id)}">Putuskan</button></div>`).join(''); document.querySelectorAll('[data-disconnect]').forEach((button) => button.addEventListener('click', async () => { await window.haloDeck.disconnectDevice(button.dataset.disconnect); showToast('Perangkat diputuskan dari sesi lokal'); })); document.querySelectorAll('[data-screen]').forEach((button) => button.addEventListener('click', () => { const device = devices.find((candidate) => candidate.id === button.dataset.screen); if (device) createOffer(device); })); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
function formatSince(timestamp) { const seconds = Math.max(0, Math.round((Date.now() - timestamp) / 1000)); return seconds < 3 ? 'baru saja' : `${seconds} dtk lalu`; }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('visible'); window.setTimeout(() => toast.classList.remove('visible'), 2300); }

function renderCaptureProfile() { const profile = captureProfiles[state.captureProfile] ?? captureProfiles.screen; document.querySelectorAll('[data-capture-profile]').forEach((button) => button.classList.toggle('active', button.dataset.captureProfile === state.captureProfile)); const note = $('#capture-note'); if (note) note.textContent = profile.note; }
function stopCapture() { state.stream?.getTracks().forEach((track) => track.stop()); state.stream = null; state.peer?.close(); state.peer = null; }
async function createOffer(device) { const profile = captureProfiles[state.captureProfile] ?? captureProfiles.screen; state.activeDevice = device; stopCapture(); state.peer = new RTCPeerConnection({ iceServers: [], bundlePolicy: 'max-bundle' }); state.peer.onicecandidate = (event) => { const candidate = event.candidate?.toJSON?.(); if (candidate?.candidate?.startsWith('candidate:') && typeof candidate.sdpMid === 'string' && Number.isInteger(candidate.sdpMLineIndex)) window.haloDeck.relaySignal({ type: 'webrtc.ice', candidate, targetDeviceId: device.id }); }; state.peer.onconnectionstatechange = () => { if (['failed', 'disconnected', 'closed'].includes(state.peer?.connectionState)) showToast('Streaming layar terputus; Pocket Hub akan meminta ulang saat koneksi LAN kembali'); }; try { state.stream = await navigator.mediaDevices.getDisplayMedia({ video: { displaySurface: profile.surface, width: { ideal: 1920 }, height: { ideal: 1080 }, frameRate: { ideal: 30, max: 30 } }, audio: false }); const track = state.stream.getVideoTracks()[0]; if (!track) throw new Error('Tidak ada sumber video'); track.contentHint = profile.contentHint; track.onended = () => { showToast('Sumber preview dihentikan'); stopCapture(); }; state.stream.getTracks().forEach((item) => state.peer.addTrack(item, state.stream)); const offer = await state.peer.createOffer(); await state.peer.setLocalDescription(offer); await window.haloDeck.relaySignal({ type: 'webrtc.offer', sdp: offer.sdp, descriptionType: 'offer', targetDeviceId: device.id }); showToast(`${profile.label[0].toUpperCase()}${profile.label.slice(1)} dikirim ke ${device.name}`); } catch (error) { stopCapture(); showToast('Sumber belum dipilih atau izin screen capture dibatalkan'); } }
async function handleSignal({ device, message }) { if (!device) return; if (message.type === 'webrtc.request') return createOffer(device); if (message.type === 'webrtc.answer' && state.peer && state.activeDevice?.id === device.id) return state.peer.setRemoteDescription({ type: 'answer', sdp: message.sdp }); if (message.type === 'webrtc.ice' && state.peer && state.activeDevice?.id === device.id) return state.peer.addIceCandidate(message.candidate); }

function wireUi() { document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => document.getElementById(button.dataset.scroll)?.scrollIntoView({ behavior: 'smooth' }))); document.querySelectorAll('[data-capture-profile]').forEach((button) => button.addEventListener('click', () => { state.captureProfile = button.dataset.captureProfile; localStorage.setItem('halo.captureProfile', state.captureProfile); renderCaptureProfile(); showToast('Profil preview diperbarui'); })); $('#refresh-button').addEventListener('click', async () => { render(await window.haloDeck.getBridgeInfo()); showToast('Status server diperbarui'); }); $('#scan-status').addEventListener('click', async () => { render(await window.haloDeck.getBridgeInfo()); showToast('Daftar perangkat diperbarui'); }); $('#copy-address').addEventListener('click', async () => { await navigator.clipboard.writeText(state.info?.address ?? ''); showToast('Alamat WebSocket disalin'); }); }

window.haloDeck.onBridgeReady(render); window.haloDeck.onDevicesUpdated((payload) => { state.devices = payload.devices ?? []; renderDevices(); if (state.devices.length) $('#last-activity').innerHTML = '<span class="activity-icon blue">▣</span><div><strong>Perangkat baru terhubung</strong><small>Pairing berhasil dan sesi tepercaya aktif</small></div><time>baru saja</time>'; }); window.haloDeck.onWebrtcSignal(handleSignal); wireUi(); window.haloDeck.getBridgeInfo().then(render);
